### ISSUE TITLE
Màn hình tạo mới chỉnh sửa account

### ISSUE THREAD

**Issue by alx-github** [alx-github/production-management-system#2]
**# Chỉ thiết kế layout, không cần xử lý. Trang 19**
![image](https://user-images.githubusercontent.com/29878557/28049230-17fcf5fe-6620-11e7-8fd0-d90796bbd536.png)

**Comment by sangpm84** [comment]
0:指定なし
1:管理者ユーザー
2:受発注ユーザー
3:裁断ユーザー
4:縫製ユーザー
5:出荷ユーザー

![28008644-5efcb490-6593-11e7-9518-14d89b8bcaf6](https://user-images.githubusercontent.com/15243802/28049350-f6479c9c-6620-11e7-891f-fcf5c91202ed.png)
